const test = require('node:test')
const assert = require('node:assert/strict')

test('usage refreshes after activity settles, never on an idle interval, and unsubscribes cleanly', async t => {
  const { watchUsageActivity } = await import('../renderer/utils/usageActivity.mjs')
  t.mock.timers.enable({ apis: ['setTimeout'] })
  const listeners = new Map()
  const subscribe = name => cb => { listeners.set(name, cb); return () => listeners.delete(name) }
  const api = { terminal: { onData: subscribe('data'), onExit: subscribe('exit') }, onAgentActivity: subscribe('activity') }
  let refreshes = 0
  const stop = watchUsageActivity(api, () => refreshes++)
  assert.equal(refreshes, 1, 'initial load')
  t.mock.timers.tick(300000)
  assert.equal(refreshes, 1, 'five idle minutes do not query usage')
  listeners.get('activity')({ state: 'working' })
  listeners.get('data')({ agentId: 'codex', chunk: 'reply' })
  t.mock.timers.tick(2000)
  listeners.get('data')({ agentId: 'claude', chunk: 'another reply' })
  listeners.get('activity')({ state: 'waiting' })
  t.mock.timers.tick(2000)
  assert.equal(refreshes, 1, 'concurrent output is debounced')
  t.mock.timers.tick(1000)
  assert.equal(refreshes, 2)
  t.mock.timers.tick(300000)
  assert.equal(refreshes, 2, 'refresh does not schedule another refresh')
  listeners.get('exit')({ id: 'terminal' })
  t.mock.timers.tick(3000)
  assert.equal(refreshes, 3)
  listeners.get('data')({ chunk: 'pending output' })
  stop()
  t.mock.timers.tick(3000)
  assert.equal(refreshes, 3)
  assert.equal(listeners.size, 0)
})
